apiVersion: v1
kind: Service
metadata: 
  name: worker-1
spec:
  selector:
    work: worker1
  ports:
    - port: 8492
      targetPort: 8492
---
apiVersion: v1
kind: Pod
metadata:
  name: test-worker1
  labels: 
    work: worker1
spec:
  containers:
  - name: test-worker1
    image: tensorflow
    command: ["/usr/bin/python3","/Distributed.py","--job_name=worker","--task_index=0"]
    imagePullPolicy: IfNotPresent
    env:
    - name: http_proxy
      value: "http://58.193.0.178:3128"
    - name: https_proxy
      value: "http://58.193.0.178:3128"
      ports:
        - containerPort: 8492
  nodeSelector: 
    tensorflow : work2
  restartPolicy: Never  
