apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
  labels:
    app: wordpress
  annotations:
    tenxcloud.com/schemaPortname: mysql-1/TCP
spec:
  ports:
    - name: mysql-1
      protocol: TCP
      targetPort: 3306
      port: 3306
  selector:
    app: wordpress
    tier: mysql
  externalIPs:
    - 11.11.1.1
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wordpress-mysql
  labels:
    app: wordpress
spec:
  template:
    metadata:
      labels:
        app: wordpress
        tier: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: admin 
        ports:
        - containerPort: 3306
          name: mysql-1
